version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  reviewers:
  - "jeger-at"
  - "mcibique"
  - "stavros-tomas"
  ignore:
  - dependency-name: clipboard-copy
    versions:
    - ">= 4"
  - dependency-name: svg-sprite-loader
    versions:
    - ">= 6"
  - dependency-name: svgo-loader
    versions:
    - ">= 3"
  - dependency-name: svgo
    versions:
    - ">= 2"
  - dependency-name: cypress
    versions:
    - ">= 6"
