version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  reviewers:
  - "corinaper"
  - "derrick-g"
  - "mcibique"
  - "stavros-tomas"
  - "wolandec"
  ignore:
  - dependency-name: cypress
    versions:
    - ">= 10"
  groups:
    storybook:
      patterns:
        - "@storybook/*"
        - "storybook*"
    vueuse:
      patterns:
        - "@vueuse/*"
    stylelint:
      patterns:
        - "stylelint*"
    postcss:
      patterns:
        - "postcss*"
        - "autoprefixer"
    eslint:
      patterns:
        - "eslint*"