/* eslint-disable array-bracket-spacing */
const plugin = require('tailwindcss/plugin');
const flattenColorPalette = require('tailwindcss/lib/util/flattenColorPalette').default;

// see https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
// for reference config
module.exports = {
  // we don't use built-in purge because:
  // 1. we have specific scenarios which we don't want to be purged -> tailwind.story.css
  // 2. we need to tweak the purgecss config in the real application
  // 3. we want to have purgecss available for other parts of the code in the future, e.g. purging other 3rd party libraries
  // so we set up purgecss manually. see: https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss-manually
  purge: false,
  prefix: 'tw-',
  important: false,
  separator: ':',
  theme: {
    screens: {
      xs: '320px',
      sm: '576px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1920px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',

      key: {
        1: 'hsl(var(--ec-key-color-level-1))',
        2: 'hsl(var(--ec-key-color-level-2))',
        3: 'hsl(var(--ec-key-color-level-3))',
        4: 'hsl(var(--ec-key-color-level-4))',
        5: 'hsl(var(--ec-key-color-level-5))',
        6: 'hsl(var(--ec-key-color-level-6))',
        7: 'hsl(var(--ec-key-color-level-7))',
      },

      gray: {
        0: 'hsl(var(--ec-gray-color-level-0))',
        1: 'hsl(var(--ec-gray-color-level-1))',
        2: 'hsl(var(--ec-gray-color-level-2))',
        3: 'hsl(var(--ec-gray-color-level-3))',
        4: 'hsl(var(--ec-gray-color-level-4))',
        5: 'hsl(var(--ec-gray-color-level-5))',
        6: 'hsl(var(--ec-gray-color-level-6))',
        7: 'hsl(var(--ec-gray-color-level-7))',
        8: 'hsl(var(--ec-gray-color-level-8))',
      },

      complementary: {
        1: 'hsl(var(--ec-complementary-color-level-1))',
        2: 'hsl(var(--ec-complementary-color-level-2))',
      },

      additional: {
        18: 'hsl(var(--ec-additional-color-level-18))',
        51: 'hsl(var(--ec-additional-color-level-51))',
        64: 'hsl(var(--ec-additional-color-level-64))',
        140: 'hsl(var(--ec-additional-color-level-140))',
        166: 'hsl(var(--ec-additional-color-level-166))',
        215: 'hsl(var(--ec-additional-color-level-215))',
        266: 'hsl(var(--ec-additional-color-level-266))',
        280: 'hsl(var(--ec-additional-color-level-280))',
        297: 'hsl(var(--ec-additional-color-level-297))',
        325: 'hsl(var(--ec-additional-color-level-325))',
      },

      error: {
        DEFAULT: 'hsl(var(--ec-reserved-color-error))',
        dark: 'hsl(var(--ec-reserved-color-error-dark))',
        light: 'hsl(var(--ec-reserved-color-error-light))',
      },

      info: {
        DEFAULT: 'hsl(var(--ec-reserved-color-info))',
        dark: 'hsl(var(--ec-reserved-color-info-dark))',
        light: 'hsl(var(--ec-reserved-color-info-light))',
      },

      success: {
        DEFAULT: 'hsl(var(--ec-reserved-color-success))',
        dark: 'hsl(var(--ec-reserved-color-success-dark))',
        light: 'hsl(var(--ec-reserved-color-success-light))',
      },

      warning: {
        DEFAULT: 'hsl(var(--ec-reserved-color-warning))',
        dark: 'hsl(var(--ec-reserved-color-warning-dark))',
        light: 'hsl(var(--ec-reserved-color-warning-light))',
      },
    },
    spacing: {
      // px: '1px',
      0: '0',
      1: '1px',
      4: '4px',
      8: '8px',
      12: '12px',
      16: '16px',
      20: '20px',
      24: '24px',
      28: '28px',
      32: '32px',
      36: '36px',
      40: '40px',
      48: '48px',
      56: '56px',
      64: '64px',
      72: '72px',
      80: '80px',
      88: '88px',
      96: '96px',
      104: '104px',
    },
    // animation: {
    //   none: 'none',
    //   spin: 'spin 1s linear infinite',
    //   ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
    //   pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    //   bounce: 'bounce 1s infinite',
    // },
    // backdropBlur: (theme) => theme('blur'),
    // backdropBrightness: (theme) => theme('brightness'),
    // backdropContrast: (theme) => theme('contrast'),
    // backdropGrayscale: (theme) => theme('grayscale'),
    // backdropHueRotate: (theme) => theme('hueRotate'),
    // backdropInvert: (theme) => theme('invert'),
    // backdropOpacity: (theme) => theme('opacity'),
    // backdropSaturate: (theme) => theme('saturate'),
    // backdropSepia: (theme) => theme('sepia'),
    backgroundColor: theme => theme('colors'),
    backgroundImage: {
      none: 'none',
      'gradient-1': 'linear-gradient(132.46deg, theme(colors.complementary.2) 21.71%, theme(colors.key.4) 73.94%)',
      'gradient-to-t': 'linear-gradient(to top, var(--tw-gradient-stops))',
      'gradient-to-tr': 'linear-gradient(to top right, var(--tw-gradient-stops))',
      'gradient-to-r': 'linear-gradient(to right, var(--tw-gradient-stops))',
      'gradient-to-br': 'linear-gradient(to bottom right, var(--tw-gradient-stops))',
      'gradient-to-b': 'linear-gradient(to bottom, var(--tw-gradient-stops))',
      'gradient-to-bl': 'linear-gradient(to bottom left, var(--tw-gradient-stops))',
      'gradient-to-l': 'linear-gradient(to left, var(--tw-gradient-stops))',
      'gradient-to-tl': 'linear-gradient(to top left, var(--tw-gradient-stops))',
    },
    // backgroundOpacity: theme => theme('opacity'),
    // backgroundPosition: {
    //   bottom: 'bottom',
    //   center: 'center',
    //   left: 'left',
    //   'left-bottom': 'left bottom',
    //   'left-top': 'left top',
    //   right: 'right',
    //   'right-bottom': 'right bottom',
    //   'right-top': 'right top',
    //   top: 'top',
    // },
    // backgroundSize: {
    //   auto: 'auto',
    //   cover: 'cover',
    //   contain: 'contain',
    // },
    blur: {
      4: '4px',
      // 0: '0',
      // none: '0',
      // sm: '4px',
      // DEFAULT: '8px',
      // md: '12px',
      // lg: '16px',
      // xl: '24px',
      // '2xl': '40px',
      // '3xl': '64px',
    },
    // brightness: {
    //   0: '0',
    //   50: '.5',
    //   75: '.75',
    //   90: '.9',
    //   95: '.95',
    //   100: '1',
    //   105: '1.05',
    //   110: '1.1',
    //   125: '1.25',
    //   150: '1.5',
    //   200: '2',
    // },
    borderColor: theme => ({
      ...theme('colors'),
      DEFAULT: theme('colors.gray.level-4', 'currentColor'),
    }),
    // borderOpacity: theme => theme('opacity'),
    borderRadius: {
      none: '0',
      sm: '2px',
      DEFAULT: '5px',
      button: '32px',
      '1/2': '50%',
    },
    borderWidth: {
      DEFAULT: '1px',
      0: '0',
      2: '2px',
      // 4: '4px',
      // 8: '8px',
    },
    boxShadow: {
      // xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
      // sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      // DEFAULT: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      // md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      // lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      // xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      // '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      // inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      // outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
      'level-0': '0 2px 4px 0 hsla(0, 0%, 0%, 0.1)',
      'level-1': '0 3px 6px 0 hsla(0, 0%, 0%, 0.2)',
      'level-1-rtl': '-3px 0 6px 0 hsla(0, 0%, 0%, 0.2)',
      'level-2': '0 10px 20px 0 hsla(0, 0%, 0%, 0.2)',
    },
    // caretColor: (theme) => theme('colors'),
    // contrast: {
    //   0: '0',
    //   50: '.5',
    //   75: '.75',
    //   100: '1',
    //   125: '1.25',
    //   150: '1.5',
    //   200: '2',
    // },
    container: {},
    // content: {
    //   none: 'none',
    // },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      text: 'text',
      move: 'move',
      help: 'help',
      'not-allowed': 'not-allowed',
    },
    // divideColor: theme => theme('borderColor'),
    // divideOpacity: theme => theme('borderOpacity'),
    // divideWidth: theme => theme('borderWidth'),
    // dropShadow: {
    //   sm: '0 1px 1px rgba(0,0,0,0.05)',
    //   DEFAULT: ['0 1px 2px rgba(0, 0, 0, 0.1)', '0 1px 1px rgba(0, 0, 0, 0.06)'],
    //   md: ['0 4px 3px rgba(0, 0, 0, 0.07)', '0 2px 2px rgba(0, 0, 0, 0.06)'],
    //   lg: ['0 10px 8px rgba(0, 0, 0, 0.04)', '0 4px 3px rgba(0, 0, 0, 0.1)'],
    //   xl: ['0 20px 13px rgba(0, 0, 0, 0.03)', '0 8px 5px rgba(0, 0, 0, 0.08)'],
    //   '2xl': '0 25px 25px rgba(0, 0, 0, 0.15)',
    //   none: '0 0 #0000',
    // },
    fill: theme => theme('colors'),
    flex: {
      1: '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexGrow: {
      0: '0',
      DEFAULT: '1',
    },
    flexShrink: {
      0: '0',
      DEFAULT: '1',
    },
    fontFamily: {
      sans: [
        // 'system-ui',
        // '-apple-system',
        // 'BlinkMacSystemFont',
        // '"Segoe UI"',
        'Roboto',
        // '"Helvetica Neue"',
        // 'Arial',
        // '"Noto Sans"',
        'sans-serif',
        // '"Apple Color Emoji"',
        // '"Segoe UI Emoji"',
        // '"Segoe UI Symbol"',
        // '"Noto Color Emoji"',
      ],
      'sans-condensed': ['Roboto Condensed', 'sans-serif'],
      // serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: ['Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
    },
    // fontSize: {
    //   xs: ['0.75rem', { lineHeight: '1rem' }],
    //   sm: ['0.875rem', { lineHeight: '1.25rem' }],
    //   base: ['1rem', { lineHeight: '1.5rem' }],
    //   lg: ['1.125rem', { lineHeight: '1.75rem' }],
    //   xl: ['1.25rem', { lineHeight: '1.75rem' }],
    //   '2xl': ['1.5rem', { lineHeight: '2rem' }],
    //   '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
    //   '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
    //   '5xl': ['3rem', { lineHeight: '1' }],
    //   '6xl': ['3.75rem', { lineHeight: '1' }],
    //   '7xl': ['4.5rem', { lineHeight: '1' }],
    //   '8xl': ['6rem', { lineHeight: '1' }],
    //   '9xl': ['8rem', { lineHeight: '1' }],
    // },
    // fontWeight: {
    //   thin: '100',
    //   extralight: '200',
    //   light: '300',
    //   normal: '400',
    //   medium: '500',
    //   semibold: '600',
    //   bold: '700',
    //   extrabold: '800',
    //   black: '900',
    // },
    // grayscale: {
    //   0: '0',
    //   DEFAULT: '100%',
    // },
    // gap: (theme) => theme('spacing'),
    gradientColorStops: theme => theme('colors'),
    // gridAutoColumns: {
    //   auto: 'auto',
    //   min: 'min-content',
    //   max: 'max-content',
    //   fr: 'minmax(0, 1fr)',
    // },
    // gridAutoRows: {
    //   auto: 'auto',
    //   min: 'min-content',
    //   max: 'max-content',
    //   fr: 'minmax(0, 1fr)',
    // },
    // gridColumn: {
    //   auto: 'auto',
    //   'span-1': 'span 1 / span 1',
    //   'span-2': 'span 2 / span 2',
    //   'span-3': 'span 3 / span 3',
    //   'span-4': 'span 4 / span 4',
    //   'span-5': 'span 5 / span 5',
    //   'span-6': 'span 6 / span 6',
    //   'span-7': 'span 7 / span 7',
    //   'span-8': 'span 8 / span 8',
    //   'span-9': 'span 9 / span 9',
    //   'span-10': 'span 10 / span 10',
    //   'span-11': 'span 11 / span 11',
    //   'span-12': 'span 12 / span 12',
    //   'span-full': '1 / -1',
    // },
    // gridColumnEnd: {
    //   auto: 'auto',
    //   1: '1',
    //   2: '2',
    //   3: '3',
    //   4: '4',
    //   5: '5',
    //   6: '6',
    //   7: '7',
    //   8: '8',
    //   9: '9',
    //   10: '10',
    //   11: '11',
    //   12: '12',
    //   13: '13',
    // },
    // gridColumnStart: {
    //   auto: 'auto',
    //   1: '1',
    //   2: '2',
    //   3: '3',
    //   4: '4',
    //   5: '5',
    //   6: '6',
    //   7: '7',
    //   8: '8',
    //   9: '9',
    //   10: '10',
    //   11: '11',
    //   12: '12',
    //   13: '13',
    // },
    // gridRow: {
    //   auto: 'auto',
    //   'span-1': 'span 1 / span 1',
    //   'span-2': 'span 2 / span 2',
    //   'span-3': 'span 3 / span 3',
    //   'span-4': 'span 4 / span 4',
    //   'span-5': 'span 5 / span 5',
    //   'span-6': 'span 6 / span 6',
    //   'span-full': '1 / -1',
    // },
    // gridRowStart: {
    //   auto: 'auto',
    //   1: '1',
    //   2: '2',
    //   3: '3',
    //   4: '4',
    //   5: '5',
    //   6: '6',
    //   7: '7',
    // },
    // gridRowEnd: {
    //   auto: 'auto',
    //   1: '1',
    //   2: '2',
    //   3: '3',
    //   4: '4',
    //   5: '5',
    //   6: '6',
    //   7: '7',
    // },
    // gridTemplateColumns: {
    //   none: 'none',
    //   1: 'repeat(1, minmax(0, 1fr))',
    //   2: 'repeat(2, minmax(0, 1fr))',
    //   3: 'repeat(3, minmax(0, 1fr))',
    //   4: 'repeat(4, minmax(0, 1fr))',
    //   5: 'repeat(5, minmax(0, 1fr))',
    //   6: 'repeat(6, minmax(0, 1fr))',
    //   7: 'repeat(7, minmax(0, 1fr))',
    //   8: 'repeat(8, minmax(0, 1fr))',
    //   9: 'repeat(9, minmax(0, 1fr))',
    //   10: 'repeat(10, minmax(0, 1fr))',
    //   11: 'repeat(11, minmax(0, 1fr))',
    //   12: 'repeat(12, minmax(0, 1fr))',
    // },
    // gridTemplateRows: {
    //   none: 'none',
    //   1: 'repeat(1, minmax(0, 1fr))',
    //   2: 'repeat(2, minmax(0, 1fr))',
    //   3: 'repeat(3, minmax(0, 1fr))',
    //   4: 'repeat(4, minmax(0, 1fr))',
    //   5: 'repeat(5, minmax(0, 1fr))',
    //   6: 'repeat(6, minmax(0, 1fr))',
    // },
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      // '1/2': '50%',
      // '1/3': '33.333333%',
      // '2/3': '66.666667%',
      // '1/4': '25%',
      // '2/4': '50%',
      // '3/4': '75%',
      // '1/5': '20%',
      // '2/5': '40%',
      // '3/5': '60%',
      // '4/5': '80%',
      // '1/6': '16.666667%',
      // '2/6': '33.333333%',
      // '3/6': '50%',
      // '4/6': '66.666667%',
      // '5/6': '83.333333%',
      full: '100%',
      screen: '100vh',
    }),
    // hueRotate: {
    //   '-180': '-180deg',
    //   '-90': '-90deg',
    //   '-60': '-60deg',
    //   '-30': '-30deg',
    //   '-15': '-15deg',
    //   0: '0deg',
    //   15: '15deg',
    //   30: '30deg',
    //   60: '60deg',
    //   90: '90deg',
    //   180: '180deg',
    // },
    inset: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('width'),
      ...negative(theme('width')),
      // '1/2': '50%',
      // '1/3': '33.333333%',
      // '2/3': '66.666667%',
      // '1/4': '25%',
      // '2/4': '50%',
      // '3/4': '75%',
      // full: '100%',
      // '-1/2': '-50%',
      // '-1/3': '-33.333333%',
      // '-2/3': '-66.666667%',
      // '-1/4': '-25%',
      // '-2/4': '-50%',
      // '-3/4': '-75%',
      // '-full': '-100%',
    }),
    // keyframes: {
    //   spin: {
    //     to: {
    //       transform: 'rotate(360deg)',
    //     },
    //   },
    //   ping: {
    //     '75%, 100%': {
    //       transform: 'scale(2)',
    //       opacity: '0',
    //     },
    //   },
    //   pulse: {
    //     '50%': {
    //       opacity: '.5',
    //     },
    //   },
    //   bounce: {
    //     '0%, 100%': {
    //       transform: 'translateY(-25%)',
    //       animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
    //     },
    //     '50%': {
    //       transform: 'none',
    //       animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
    //     },
    //   },
    // },
    // invert: {
    //   0: '0',
    //   DEFAULT: '100%',
    // },
    // letterSpacing: {
    //   tighter: '-0.05em',
    //   tight: '-0.025em',
    //   normal: '0em',
    //   wide: '0.025em',
    //   wider: '0.05em',
    //   widest: '0.1em',
    // },
    // lineHeight: {
    //   none: '1',
    //   tight: '1.25',
    //   snug: '1.375',
    //   normal: '1.5',
    //   relaxed: '1.625',
    //   loose: '2',
    //   3: '.75rem',
    //   4: '1rem',
    //   5: '1.25rem',
    //   6: '1.5rem',
    //   7: '1.75rem',
    //   8: '2rem',
    //   9: '2.25rem',
    //   10: '2.5rem',
    // },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    maxHeight: {
      // ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    },
    maxWidth: (theme, { breakpoints }) => ({
      none: 'none',
      paragraph: '75ch',
      // 0: '0rem',
      // xs: '20rem',
      // sm: '24rem',
      // md: '28rem',
      // lg: '32rem',
      // xl: '36rem',
      // '2xl': '42rem',
      // '3xl': '48rem',
      // '4xl': '56rem',
      // '5xl': '64rem',
      // '6xl': '72rem',
      // '7xl': '80rem',
      full: '100%',
      // min: 'min-content',
      // max: 'max-content',
      // prose: '65ch',
      ...breakpoints(theme('screens')),
    }),
    minHeight: theme => ({
      ...theme('spacing'),
      // 0: '0px',
      full: '100%',
      screen: '100vh',
    }),
    minWidth: theme => ({
      ...theme('spacing'),
      // 0: '0px',
      full: '100%',
      // min: 'min-content',
      // max: 'max-content',
    }),
    // objectPosition: {
    //   bottom: 'bottom',
    //   center: 'center',
    //   left: 'left',
    //   'left-bottom': 'left bottom',
    //   'left-top': 'left top',
    //   right: 'right',
    //   'right-bottom': 'right bottom',
    //   'right-top': 'right top',
    //   top: 'top',
    // },
    opacity: {
      0: '0',
      // 5: '0.05',
      // 10: '0.1',
      // 20: '0.2',
      // 25: '0.25',
      // 30: '0.3',
      // 40: '0.4',
      // 50: '0.5',
      // 60: '0.6',
      // 70: '0.7',
      // 75: '0.75',
      // 80: '0.8',
      // 90: '0.9',
      // 95: '0.95',
      100: '1',
    },
    order: {
      // first: '-9999',
      // last: '9999',
      none: '0',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
    },
    outline: {
      none: ['2px solid transparent', '2px'],
      // white: ['2px dotted white', '2px'],
      // black: ['2px dotted black', '2px'],
    },
    padding: theme => theme('spacing'),
    // placeholderColor: theme => theme('colors'),
    // placeholderOpacity: theme => theme('opacity'),
    // ringColor: (theme) => ({
    //   DEFAULT: theme('colors.blue.500', '#3b82f6'),
    //   ...theme('colors'),
    // }),
    // ringOffsetColor: (theme) => theme('colors'),
    // ringOffsetWidth: {
    //   0: '0px',
    //   1: '1px',
    //   2: '2px',
    //   4: '4px',
    //   8: '8px',
    // },
    // ringOpacity: (theme) => ({
    //   DEFAULT: '0.5',
    //   ...theme('opacity'),
    // }),
    // ringWidth: {
    //   DEFAULT: '3px',
    //   0: '0px',
    //   1: '1px',
    //   2: '2px',
    //   4: '4px',
    //   8: '8px',
    // },
    rotate: {
      '-360': '-360deg',
      '-180': '-180deg',
      '-90': '-90deg',
      '-45': '-45deg',
      // '-12': '-12deg',
      // '-6': '-6deg',
      // '-3': '-3deg',
      // '-2': '-2deg',
      // '-1': '-1deg',
      0: '0deg',
      // 1: '1deg',
      // 2: '2deg',
      // 3: '3deg',
      // 6: '6deg',
      // 12: '12deg',
      45: '45deg',
      90: '90deg',
      180: '180deg',
      360: '360deg',
    },
    // saturate: {
    //   0: '0',
    //   50: '.5',
    //   100: '1',
    //   150: '1.5',
    //   200: '2',
    // },
    // scale: {
    //   0: '0',
    //   50: '.5',
    //   75: '.75',
    //   90: '.9',
    //   95: '.95',
    //   100: '1',
    //   105: '1.05',
    //   110: '1.1',
    //   125: '1.25',
    //   150: '1.5',
    // },
    // sepia: {
    //   0: '0',
    //   DEFAULT: '100%',
    // },
    // skew: {
    //   '-12': '-12deg',
    //   '-6': '-6deg',
    //   '-3': '-3deg',
    //   '-2': '-2deg',
    //   '-1': '-1deg',
    //   0: '0deg',
    //   1: '1deg',
    //   2: '2deg',
    //   3: '3deg',
    //   6: '6deg',
    //   12: '12deg',
    // },
    // space: (theme, { negative }) => ({
    //   ...theme('spacing'),
    //   ...negative(theme('spacing')),
    // }),
    stroke: theme => theme('colors'),
    strokeWidth: {
      0: '0',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
    },
    textColor: theme => theme('colors'),
    // textOpacity: theme => theme('opacity'),
    // transformOrigin: {
    //   center: 'center',
    //   top: 'top',
    //   'top-right': 'top right',
    //   right: 'right',
    //   'bottom-right': 'bottom right',
    //   bottom: 'bottom',
    //   'bottom-left': 'bottom left',
    //   left: 'left',
    //   'top-left': 'top left',
    // },
    transitionDelay: {
      75: '75ms',
      100: '100ms',
      150: '150ms',
      200: '200ms',
      300: '300ms',
      500: '500ms',
      700: '700ms',
      1000: '1000ms',
    },
    transitionDuration: {
      0: '0ms',
      // DEFAULT: '150ms',
      75: '75ms',
      100: '100ms',
      150: '150ms',
      200: '200ms',
      300: '300ms',
      400: '400ms',
      500: '500ms',
      700: '700ms',
      1000: '1000ms',
    },
    transitionProperty: {
      none: 'none',
      all: 'all',
      DEFAULT: 'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
      colors: 'background-color, border-color, color, fill, stroke',
      text: 'color',
      opacity: 'opacity',
      shadow: 'box-shadow',
      transform: 'transform',
      'transform-opacity': 'transform, opacity',
    },
    transitionTimingFunction: {
      // due to a bug in TW2 the DEFAULT values are ignored,
      // so tw-ease doesn't work.
      // Created tw-ease-default instead.
      // DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      // DEFAULT: 'ease',
      default: 'ease',
      linear: 'linear',
      in: 'ease-in',
      out: 'ease-out',
      'in-out': 'ease-in-out',
      // in: 'cubic-bezier(0.4, 0, 1, 1)',
      // out: 'cubic-bezier(0, 0, 0.2, 1)',
      // 'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    translate: {
      // ...theme('spacing'),
      // ...negative(theme('spacing')),
      '1/2': '50%',
      // '1/3': '33.333333%',
      // '2/3': '66.666667%',
      // '1/4': '25%',
      // '2/4': '50%',
      // '3/4': '75%',
      full: '100%',
      '-1/2': '-50%',
      // '-1/3': '-33.333333%',
      // '-2/3': '-66.666667%',
      // '-1/4': '-25%',
      // '-2/4': '-50%',
      // '-3/4': '-75%',
      '-full': '-100%',
    },
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '3/3': '100%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '4/4': '100%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '5/5': '100%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '6/6': '100%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      '12/12': '100%',
      full: '100%',
      screen: '100vw',
      // min: 'min-content',
      // max: 'max-content',
    }),
    zIndex: {
      0: 0,
      auto: 'auto',
      navigation: 1,
      notification: 300,
      loading: 250,
      modal: 200,
      tooltip: 100,
      'level-1': 10,
      'level-2': 20,
      'level-3': 30,
    },
    typography: theme => ({
      h1: { fontSize: '35px', lineHeight: '40px', fontWeight: 400 },
      h2: { fontSize: '25px', lineHeight: '35px', fontWeight: 300 },
      h3: { fontSize: '20px', lineHeight: '30px', fontWeight: 500 },
      h4: { fontSize: '18px', lineHeight: '24px', fontWeight: 300 },
      h5: { fontSize: '16px', lineHeight: '26px', fontWeight: 500 },
      h6: {
        fontSize: '14px', lineHeight: '24px', fontWeight: 500, textTransform: 'uppercase',
      },
      'body-text': { fontSize: '16px', lineHeight: '24px', fontWeight: 400 },
      'body-strong': { fontSize: '16px', lineHeight: '24px', fontWeight: 700 },
      'body-condensed': {
        fontSize: '16px', lineHeight: '24px', fontWeight: 400, fontFamily: theme('fontFamily.sans-condensed').join(', '),
      },
      'small-text': { fontSize: '14px', lineHeight: '20px', fontWeight: 400 },
      'small-strong': { fontSize: '14px', lineHeight: '20px', fontWeight: 700 },
      'mini-header': {
        fontSize: '14px', lineHeight: '20px', fontWeight: 400, color: theme('textColor.gray.5'), textTransform: 'uppercase',
      },
      'caption-text': {
        fontSize: '14px', lineHeight: '20px', fontWeight: 400, color: theme('textColor.gray.5'),
      },
      'input-label': {
        fontSize: '14px', lineHeight: '20px', fontWeight: 700, color: theme('textColor.gray.3'),
      },
      'table-header': {
        fontSize: '14px', lineHeight: '20px', fontWeight: 700, color: theme('textColor.gray.5'),
      },
      'btn-text': { fontSize: '16px', lineHeight: '22px', fontWeight: 400 },
      'flags-text': { fontSize: '12px', lineHeight: '20px', fontWeight: 400 },
      'help-text': { fontSize: '12px', lineHeight: '16px', fontWeight: 400 },
    }),
  },
  variantOrder: [
    'first',
    'last',
    'odd',
    'even',
    'visited',
    'checked',
    'empty',
    'read-only',
    'group-hover',
    'group-focus',
    'focus-within',
    'hover',
    'focus',
    'focus-visible',
    'active',
    'disabled',
  ],
  variants: {
    accessibility: [ /* 'responsive', 'focus-within', 'focus' */ ],
    alignContent: [ /* 'responsive' */ ],
    alignItems: [ /* 'responsive' */ ],
    alignSelf: [ /* 'responsive' */ ],
    animation: [ /* 'responsive' */ ],
    appearance: [ /* 'responsive' */ ],
    backdropBlur: [ /* 'responsive' */ ],
    backdropBrightness: [ /* 'responsive' */ ],
    backdropContrast: [ /* 'responsive' */ ],
    backdropFilter: [ /* 'responsive' */ ],
    backdropGrayscale: [ /* 'responsive' */ ],
    backdropHueRotate: [ /* 'responsive' */ ],
    backdropInvert: [ /* 'responsive' */ ],
    backdropOpacity: [ /* 'responsive' */ ],
    backdropSaturate: [ /* 'responsive' */ ],
    backdropSepia: [ /* 'responsive' */ ],
    backgroundAttachment: [ /* 'responsive' */ ],
    backgroundBlendMode: [ /* 'responsive' */ ],
    backgroundClip: [ /* 'responsive' */ ],
    backgroundColor: [ /* 'responsive', 'dark', 'group-hover', 'focus-within', */ 'hover', 'focus' ],
    backgroundImage: [ 'responsive' ],
    backgroundOpacity: [ /* 'responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    backgroundPosition: [ /* 'responsive' */ ],
    backgroundRepeat: [ /* 'responsive' */ ],
    backgroundSize: [ /* 'responsive' */ ],
    backgroundOrigin: [ /* 'responsive' */ ],
    blur: [ /* 'responsive' */ ],
    borderCollapse: [ /* 'responsive' */ ],
    borderColor: [ /* 'responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    borderOpacity: [ /* 'responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    borderRadius: [ /* 'responsive' */ ],
    borderStyle: [ /* 'responsive' */ ],
    borderWidth: [ /* 'responsive' */ ],
    boxDecorationBreak: [ /* 'responsive' */ ],
    boxShadow: [ /* 'responsive', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    boxSizing: [ /* 'responsive' */ ],
    brightness: [ /* 'responsive' */ ],
    clear: [ /* 'responsive' */ ],
    container: [ /* 'responsive' */ ],
    contrast: [ /* 'responsive' */ ],
    cursor: [ /* 'responsive' */ ],
    display: [ 'responsive' ],
    divideColor: [ /* 'responsive', 'dark' */ ],
    divideOpacity: [ /* 'responsive', 'dark' */ ],
    divideStyle: [ /* 'responsive' */ ],
    divideWidth: [ /* 'responsive' */ ],
    dropShadow: [ /* 'responsive' */ ],
    fill: [ /* 'responsive', */ 'hover', 'focus' ],
    filter: [ /* 'responsive' */ ],
    flex: [ 'responsive' ],
    flexDirection: [ 'responsive' ],
    flexGrow: [ /* 'responsive' */ ],
    flexShrink: [ /* 'responsive' */ ],
    flexWrap: [ 'responsive' ],
    float: [ /* 'responsive' */ ],
    fontFamily: [ /* 'responsive' */ ],
    fontSize: [ /* 'responsive' */ ],
    fontSmoothing: [ /* 'responsive' */ ],
    fontStyle: [ /* 'responsive' */ ],
    fontVariantNumeric: [ /* 'responsive' */ ],
    fontWeight: [ /* 'responsive' */ ],
    gap: [ /* 'responsive' */ ],
    gradientColorStops: [ /* 'responsive', 'dark', */ 'hover', 'focus' ],
    grayscale: [ /* 'responsive' */ ],
    gridAutoColumns: [ /* 'responsive' */ ],
    gridAutoFlow: [ /* 'responsive' */ ],
    gridAutoRows: [ /* 'responsive' */ ],
    gridColumn: [ /* 'responsive' */ ],
    gridColumnEnd: [ /* 'responsive' */ ],
    gridColumnStart: [ /* 'responsive' */ ],
    gridRow: [ /* 'responsive' */ ],
    gridRowEnd: [ /* 'responsive' */ ],
    gridRowStart: [ /* 'responsive' */ ],
    gridTemplateColumns: [ /* 'responsive' */ ],
    gridTemplateRows: [ /* 'responsive' */ ],
    height: [ /* 'responsive' */ ],
    hueRotate: [ /* 'responsive' */ ],
    inset: [ /* 'responsive' */ ],
    invert: [ /* 'responsive' */ ],
    isolation: [ /* 'responsive' */ ],
    justifyContent: [ /* 'responsive' */ ],
    justifyItems: [ /* 'responsive' */ ],
    justifySelf: [ /* 'responsive' */ ],
    letterSpacing: [ /* 'responsive' */ ],
    lineHeight: [ /* 'responsive' */ ],
    listStylePosition: [ /* 'responsive' */ ],
    listStyleType: [ /* 'responsive' */ ],
    margin: [ 'responsive' ],
    maxHeight: [ /* 'responsive' */ ],
    maxWidth: [ /* 'responsive' */ ],
    minHeight: [ /* 'responsive' */ ],
    minWidth: [ /* 'responsive' */ ],
    mixBlendMode: [ /* 'responsive' */ ],
    objectFit: [ /* 'responsive' */ ],
    objectPosition: [ /* 'responsive' */ ],
    opacity: [ /* 'responsive', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    order: [ /* 'responsive' */ ],
    outline: [ /* 'responsive', 'focus-within', 'focus' */ ],
    overflow: [ /* 'responsive' */ ],
    overscrollBehavior: [ /* 'responsive' */ ],
    padding: [ 'responsive' ],
    placeContent: [ /* 'responsive' */ ],
    placeItems: [ /* 'responsive' */ ],
    placeSelf: [ /* 'responsive' */ ],
    placeholderColor: [ /* 'responsive', 'dark', 'focus' */ ],
    placeholderOpacity: [ /* 'responsive', 'dark', 'focus' */ ],
    pointerEvents: [ /* 'responsive' */ ],
    position: [ /* 'responsive' */ ],
    resize: [ /* 'responsive' */ ],
    ringColor: [ /* 'responsive', 'dark', 'focus-within', 'focus' */ ],
    ringOffsetColor: [ /* 'responsive', 'dark', 'focus-within', 'focus' */ ],
    ringOffsetWidth: [ /* 'responsive', 'focus-within', 'focus' */ ],
    ringOpacity: [ /* 'responsive', 'dark', 'focus-within', 'focus' */ ],
    ringWidth: [ /* 'responsive', 'focus-within', 'focus' */ ],
    rotate: [ /* 'responsive', 'hover', 'focus' */ ],
    saturate: [ /* 'responsive' */ ],
    scale: [ /* 'responsive', 'hover', 'focus' */ ],
    sepia: [ /* 'responsive' */ ],
    skew: [ /* 'responsive', 'hover', 'focus' */ ],
    space: [ /* 'responsive' */ ],
    stroke: [ /* 'responsive' */ ],
    strokeWidth: [ /* 'responsive' */ ],
    tableLayout: [ /* 'responsive' */ ],
    textAlign: [ 'responsive' ],
    textColor: [ 'responsive', 'hover', 'focus' /* 'dark', 'group-hover', 'focus-within' */ ],
    textDecoration: [ /* 'responsive', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    textOpacity: [ /* 'responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus' */ ],
    textOverflow: [ /* 'responsive' */ ],
    textTransform: [ /* 'responsive' */ ],
    transform: [ /* 'responsive' */ ],
    transformOrigin: [ /* 'responsive' */ ],
    transitionDelay: [ /* 'responsive' */ ],
    transitionDuration: [ /* 'responsive' */ ],
    transitionProperty: [ /* 'responsive' */ ],
    transitionTimingFunction: [ /* 'responsive' */ ],
    translate: [ /* 'responsive', 'hover', 'focus' */ ],
    typography: [],
    userSelect: [ /* 'responsive' */ ],
    verticalAlign: [ /* 'responsive' */ ],
    visibility: [ /* 'responsive' */ ],
    whitespace: [ /* 'responsive' */ ],
    width: [ 'responsive' ],
    wordBreak: [ /* 'responsive' */ ],
    zIndex: [ /* 'responsive', 'focus-within', 'focus' */ ],
  },
  corePlugins: {
    // https://github.com/tailwindlabs/tailwindcss/blob/v2.2.7/src/plugins/index.js
    preflight: false, // we have our own reset/normalize process

    container: true,

    accessibility: true,
    pointerEvents: true,
    visibility: true,
    position: true,
    inset: true,
    isolation: true,
    zIndex: true,
    order: true,
    gridColumn: true,
    gridColumnStart: true,
    gridColumnEnd: true,
    gridRow: true,
    gridRowStart: true,
    gridRowEnd: true,
    float: false, // we don't use floats
    clear: false, // we don't use floats
    margin: true,
    boxSizing: false, // very rarely used
    display: true,
    height: true,
    maxHeight: true,
    minHeight: true,
    width: true,
    minWidth: true,
    maxWidth: true,
    flex: true,
    flexShrink: true,
    flexGrow: true,
    tableLayout: true,
    borderCollapse: false, // we need this only for a table

    transformOrigin: true,
    translate: true,
    rotate: true,
    skew: true,
    scale: true,
    transform: true,

    animation: false, // we don't use built-in animations

    cursor: true,
    userSelect: true,
    resize: true,

    listStylePosition: false, // very rarely used
    listStyleType: true,

    appearance: false, // we build custom components
    gridAutoColumns: false, // we don't use CSS grid
    gridAutoFlow: false, // we don't use CSS grid
    gridAutoRows: false, // we don't use CSS grid
    gridTemplateColumns: false, // we don't use CSS grid
    gridTemplateRows: false, // we don't use CSS grid
    flexDirection: true,
    flexWrap: true,
    placeContent: true,
    placeItems: true,
    alignContent: true,
    alignItems: true,
    justifyContent: true,
    justifyItems: true,
    gap: false, // we don't use CSS grid
    space: false, // it's going against BEM
    divideWidth: false, // it's going against BEM
    divideStyle: false, // it's going against BEM
    divideColor: false, // it's going against BEM
    divideOpacity: false, // it's going against BEM

    placeSelf: true,
    alignSelf: true,
    justifySelf: true,

    overflow: true,
    overscrollBehavior: true,
    textOverflow: true,
    whitespace: true,
    wordBreak: true,

    borderRadius: true,
    borderWidth: true,
    borderStyle: true,
    borderColor: true,
    borderOpacity: false, // very rarely used

    backgroundColor: true,
    backgroundOpacity: true,
    backgroundImage: true,
    gradientColorStops: true,
    boxDecorationBreak: true,
    backgroundSize: false, // very rarely used
    backgroundAttachment: false, // very rarely used
    backgroundClip: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundOrigin: true,

    fill: true,
    stroke: true,
    strokeWidth: true,

    objectFit: true,
    objectPosition: true,

    padding: true,

    textAlign: true,
    verticalAlign: true,
    fontFamily: true,
    fontSize: false, // we have custom typography
    fontWeight: false, // we have custom typography
    textTransform: true,
    fontStyle: false, // we have custom typography
    fontVariantNumeric: false, // very rarely used
    lineHeight: false, // we have custom typography
    letterSpacing: false, // we have custom typography
    textColor: true,
    textOpacity: false, // very rarely used
    textDecoration: true,
    fontSmoothing: false, // who needs to change it in components?
    placeholderColor: false, // very rarely used
    placeholderOpacity: false, // very rarely used
    caretColor: false, // very rarely used

    opacity: true,
    backgroundBlendMode: false, // very rarely used
    mixBlendMode: false, // very rarely used
    boxShadow: true,
    outline: true,
    ringWidth: false, // very rarely used
    ringColor: false, // very rarely used
    ringOpacity: false, // very rarely used
    ringOffsetWidth: false, // very rarely used
    ringOffsetColor: false, // very rarely used

    blur: true,
    brightness: true,
    contrast: true,
    dropShadow: true,
    grayscale: true,
    hueRotate: true,
    invert: true,
    saturate: true,
    sepia: true,
    filter: true,

    backdropBlur: false, // very rarely used
    backdropBrightness: false, // very rarely used
    backdropContrast: false, // very rarely used
    backdropGrayscale: false, // very rarely used
    backdropHueRotate: false, // very rarely used
    backdropInvert: false, // very rarely used
    backdropOpacity: false, // very rarely used
    backdropSaturate: false, // very rarely used
    backdropSepia: false, // very rarely used
    backdropFilter: false, // very rarely used

    transitionProperty: true,
    transitionDelay: true,
    transitionDuration: true,
    transitionTimingFunction: true,

    content: true,
  },
  plugins: [
    plugin(typographyPlugin),
    plugin(flexboxGridPlugin),
    plugin(stopColorPlugin),
  ],
};

function typographyPlugin({ addUtilities, theme, e }) {
  const typography = theme('typography');
  const newUtilities = {};
  for (const [name, style] of Object.entries(typography)) {
    newUtilities[`.${e(name)}`] = style;
  }
  addUtilities(newUtilities);
}

function flexboxGridPlugin({ addUtilities, theme }) {
  // see https://getbootstrap.com/docs/4.0/layout/grid/ for reference
  const { gutter = 24, numberOfColumns = 12 } = theme('flexboxGrid', {});

  if (gutter % 2 !== 0) {
    throw new Error('Gutter must be divisible by 2');
  }

  if (numberOfColumns <= 0) {
    throw new Error('Number of columns must be a positive number');
  }

  const config = {
    variants: ['responsive'],
  };

  addUtilities({
    '.grid-container': {
      width: '100%',
      paddingRight: theme(`padding.${gutter / 2}`),
      paddingLeft: theme(`padding.${gutter / 2}`),
    },
    '.grid': {
      display: 'flex',
      flexWrap: 'wrap',
      marginRight: theme(`margin.${gutter / -2}`),
      marginLeft: theme(`margin.${gutter / -2}`),
    },
  }, config);

  const colClasses = [];
  for (let i = 1; i <= numberOfColumns; i++) {
    colClasses.push(`.col-${i}`);
  }

  for (const colClass of ['.col-full', '.col', '.col-auto', ...colClasses]) {
    addUtilities({
      [colClass]: {
        width: '100%',
        padding: theme(`padding.${gutter / 2}`),
        minHeight: theme('minHeight.1'),
      },
    }, config);
  }

  for (const colClass of ['.col', ...colClasses]) {
    addUtilities({
      [colClass]: {
        maxWidth: '100%',
        flexGrow: 1,
        flexBasis: 0,
      },
    }, config);
  }

  for (let i = 1; i <= numberOfColumns; i++) {
    const percentage = theme(`width.${i}/${numberOfColumns}`);
    addUtilities({
      [`.col-${i}`]: {
        flex: `0 0 ${percentage}`,
        maxWidth: `${percentage}`,
      },
      [`.offset-${i}`]: {
        marginLeft: `${percentage}`,
      },
    }, config);
  }

  addUtilities({
    '.col-auto': {
      flex: '0 0 auto',
      maxWidth: 'none',
      width: 'auto',
    },
  }, config);
}

function stopColorPlugin({ matchUtilities, theme }) {
  matchUtilities({
    stop: value => ({
      'stop-color': value,
    }),
  }, {
    values: flattenColorPalette(theme('colors')),
  });
}
