version: 2.1
jobs:
  build:
    working_directory: ~/chameleon
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install dependencies
          command: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint:no-fix
      - run:
          name: test
          command: npm run test -- --max-workers=2
      - run:
          name: test:cy
          command: npm run test:cy -- --spec '**/ec-input-field.cy.ts'
      - store_artifacts:
          path: ~/chameleon/tests/integration/screenshots
      - store_artifacts:
          path: ~/chameleon/tests/integration/snapshots

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
