version: 2.1
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm lint
      - run:
          name: test
          command: npm test
