version: 2.1
jobs:
  build:
    working_directory: ~/chameleon
    docker:
      - image: cypress/base:16.18.1
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint:no-fix
      - run:
          name: test
          command: npm run test -- --max-workers=2
      - run:
          name: test:cy
          command: npm run test:cy -- --spec '**/ec-input-field.cy.ts'
      - store_artifacts:
          path: ~/chameleon/tests/integration/screenshots

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
