version: 2.1
jobs:
  build:
    working_directory: ~/chameleon
    docker:
      - image: cypress/included:12.2.0
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint:no-fix
      - run:
          name: Start virtual monitor
          command:  export DISPLAY=:1
                    Xvfb :1 -screen 0 1024x768x16 2>/dev/null &
      - run:
          name: test:cy
          command: npm run test:cy -- --spec '**/ec-input-field.cy.ts'
      - run:
          name: unset DISPLAY
          command: kill %1
      - run:
          name: test
          command: npm run test -- --max-workers=2
      - store_artifacts:
          path: ~/chameleon/tests/integration/screenshots
      - store_artifacts:
          path: ~/chameleon/tests/integration/snapshots

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
