version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    working_directory: ~/chameleon
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install
          command: CYPRESS_INSTALL_BINARY=0 npm ci
      - run:
          name: lint
          command: npm run lint:no-fix
      - run:
          name: test
          command: npm run test -- --max-workers=2

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
      - cypress/run:
          component: true
