name: GitHub Actions - Check PR Title
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  Jira-PR-Title:
    if: ${{ (github.actor != 'dependabot[bot]') && (github.actor != 'EburyCrowdin') }}
    uses: Ebury/github-tools/.github/workflows/check-pr-title-reusable-workflow.yml@master

