name: Chameleon Components CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: CYPRESS_INSTALL_BINARY=0 npm ci
      - name: Lint
        run: npm run lint:no-fix
      - name: Test
        run: |
          npm run test
          output=$(git ls-files --others --modified --deleted --exclude-standard)
          [[ -z "$output" ]] || { echo "Following files were added, modified or deleted while running tests: $output"; exit 1; }
